datacenter/urls.py
from django.urls import path
from datacenter import views

app_name = 'datacenter'


urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    #(CRUD)
    path('datacenter/<int:cable_nep>/', views.cable, name='cable'),
    path('datacenter/create/', views.create, name='create'),
    path('datacenter/<int:cable_nep>/update/', views.update, name='update'),
    path('datacenter/<int:cable_nep>/delete/', views.delete, name='delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('datacenter.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

datacenter/models.py
from django.db import models

class Device(models.Model):
    name = models.CharField(max_length=50, null=False)
    vendor = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=255, blank=True)

    def __str__(self) -> str:
        return self.name

class Group(models.Model):
    group_dev = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.group_dev

class Cable(models.Model):
    nep = models.PositiveBigIntegerField(default=0, unique=True)
    dev_a = models.ForeignKey(
        Device,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name="dev_a"
    )
    ponta_a = models.CharField(max_length=50)
    dev_b = models.ForeignKey(
        Device,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name="dev_b"
    )
    ponta_b = models.CharField(max_length=50)
    group_dev = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name= 'Group',
    )
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self) -> str:
        return f'NEP: {self.nep} | Ponta A: {self.ponta_a} | Ponta B: {self.ponta_b}'

datacenter/forms.py
from django.core.exceptions import ValidationError
from django import forms

from datacenter.models import Cable

class CableForm(forms.ModelForm):
    ponta_a = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Example : XGI 0/0/0'
            }
        ),
        help_text='Por Favor não macaquear o programa'
    )
    ponta_b = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Example : XGI 0/0/0'
            }
        ),
        help_text='Escolha sabiamente entre : XGI ETH, Gb ETH,TENGb ETH,100Gb ETH,ETH TRUNK'
    )
    class Meta:
        model = Cable
        fields = (
            'nep',
            'dev_a',
            'ponta_a',
            'dev_b',
            'ponta_b',
            'description',
            'group_dev',
        )
    
    #def clean(self):
# self.
    #return super().clean()
    
    
    def clean_nep(self):
        nep = self.cleaned_data.get('nep')
        if self.instance and self.instance.pk:  # Verifica se o formulário está atualizando um cabo existente
            original_nep = Cable.objects.get(pk=self.instance.pk).nep
            if original_nep != nep:  # Se o NEP foi alterado
                if Cable.objects.filter(nep=nep).exists():
                    raise ValidationError("Já existe um cabo com este NEP.")
        else:  # Se o formulário está criando um novo cabo
            if Cable.objects.filter(nep=nep).exists():
                raise ValidationError("Já existe um cabo com este NEP.")
        return nep
    
    def clean(self):
        cleaned_data = super().clean()
        dev_a = cleaned_data.get('dev_a')
        dev_b = cleaned_data.get('dev_b')

        if not dev_a and not dev_b:
            raise ValidationError("Ambos os campos dev_a e dev_b não podem ser nulos.")
        elif dev_a and dev_b and dev_a == dev_b:
            raise ValidationError("Ta macaqueando rapaz? Onde já se viu colocar duas pontas do mesmo cabo no mesmo dispositivo?")

        return cleaned_data

datacenter/views/datacenter_forms.py
from django.shortcuts import render, get_object_or_404, redirect
from datacenter.models import Cable
from datacenter.forms import CableForm
from django.urls import reverse
from django.contrib import messages

# Função para criar um novo cabo
def create(request):
    form_action = reverse('datacenter:create')

    if request.method == 'POST':
        form = CableForm(request.POST)

        if form.is_valid():
            # Verifica se os dados do formulário já existem
            existing_cable = Cable.objects.filter(**form.cleaned_data).first()
            if existing_cable:
                messages.warning(request, 'Os dados já existem. Nenhuma alteração foi feita.')
            else:
                cable = form.save()
                messages.success(request, 'O cabo foi criado com sucesso!')
                return redirect('datacenter:update', cable_nep=cable.nep)

        return render(
            request,
            'datacenter/create.html',
            {'form': form, 'form_action': form_action},
        )

    return render(
        request,
        'datacenter/create.html',
        {'form': CableForm(), 'form_action': form_action},
    )

# Função para atualizar um cabo existente
def update(request, cable_nep):
    cable = get_object_or_404(Cable, nep=cable_nep)
    form_action = reverse('datacenter:update', args=(cable_nep,))

    if request.method == 'POST':
        form = CableForm(request.POST, instance=cable)

        if form.is_valid():
            # Verifica se os dados do formulário foram alterados
            if form.has_changed():
                cable = form.save()
                messages.success(request, 'A alteração foi um sucesso!')
            else:
                messages.info(request, 'Não há alterações nos dados.')

            return redirect('datacenter:update', cable_nep=cable.nep)

        return render(
            request,
            'datacenter/create.html',
            {'form': form, 'form_action': form_action},
        )

    return render(
        request,
        'datacenter/create.html',
        {'form': CableForm(instance=cable), 'form_action': form_action},
    )

def delete(request, cable_nep):
    cable = get_object_or_404(Cable, nep=cable_nep)
    cable.delete()
    return redirect('datacenter:index')

#    confirmation = request.POST.get('confirmation', 'no')

#    if confirmation == 'yes':
#        cable.delete()
#        return redirect('datacenter:index')
    
#    return render(
#        request,
#        'datacenter/cable.html',        {
#            'datacenter': cable,
#            'confirmation': confirmation,
#        }
#    )

datacenter/views/datacenter_views.py
from django.shortcuts import render,  get_object_or_404, redirect
from django.db.models import Q
from datacenter.models import Cable
from django.core.paginator import Paginator

# Create your views here.

def index(request):

    cables = Cable.objects\
        .filter()\
        .order_by('-nep')
    
    paginator = Paginator(cables, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    

    context = {
        'page_obj': page_obj,
        'title': 'Cables -'
    }

    return render (
        request,
        'datacenter/index.html',
        context,
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('datacenter:index')

    cables = Cable.objects\
        .select_related('dev_a', 'dev_b', 'group_dev')\
        .filter(
            Q(nep__icontains=search_value) |
            Q(dev_a__name__icontains=search_value) |
            Q(dev_b__name__icontains=search_value) |
            Q(description__icontains=search_value) |
            Q(group_dev__group_dev__icontains=search_value),
        )\
        .order_by('-nep')
    
    paginator = Paginator(cables, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    print(cables.query)

    context = {
        'page_obj': page_obj,
        'title': 'Search -',
        'search_value': search_value,

    }

    return render (
        request,
        'datacenter/index.html',
        context,
    )

def cable(request, cable_nep):
    single_cable = get_object_or_404(
        Cable, nep=cable_nep
    )

    site_title = f'{single_cable.nep} -'
    
    context = {
        'cable': single_cable, 
        'site_title' : site_title,
    }

    return render(
        request,
        'datacenter/cable.html',
        context,
    )

datacenter/templates/datacenter/cable.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-cable">
        <h1 class="single-cable-data">
            {{cable.dev_a}} -> TO -> {{cable.dev_b}}
        </h1>
        <h2><b>NEP: </b>{{cable.nep}}</h2>
        <h2><b>Ponta A: </b>{{cable.ponta_a}}</h2>
        <h2><b>Ponta B: </b>{{cable.ponta_b}}</h2>
        <h2><b>Group: </b>{{cable.group_dev}}</h2>
        <h2><b>Description: </b>{{cable.description}}</h2>

        <div class="cable-links">
            <a class="btn btn-link" href="{% url "datacenter:update" cable.nep%}">Update</a>

            <form action="{% url "datacenter:delete" cable.nep %}" method="POST">
                {% csrf_token %}

                {% if  confirmation == 'no'%}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class ="btn btn-link btn-delete" type="submit">Confirma?</button>
                {% else %}
                <button class ="btn btn-link btn-delete" type="submit">Delete</button>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock content %}

datacenter/templates/datacenter/create.html
{% extends "global/base.html" %}

{% block content %}
  <div class="form-wrapper">

    <h2>CABLE</h2>

    <form   
      action="{{form.action}}"
      method="POST"
      enctype="multipart/form-data"
    >
    
      {% csrf_token %}

      <div class="form-content">
        {% if form.non_field_errors %}
        <div class="form-group">
            <div class="message error">
            {{ form.non_field_errors}}
            </div>
        </div>
        {% endif %}

        {% if messages %}
        <div class="form-group">
            <div class="message success">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
            </div>
        </div>
        {% endif %}

        {% for field in form %}   
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{field.errors}}

          {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

datacenter/templates/datacenter/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="cable-table">
            <caption class="table-caption">
                LISTA DE CABOS
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">NEP</th>
                    <th class="table-header">Device A</th>
                    <th class="table-header">Ponta A</th>
                    <th class="table-header">Device B</th>
                    <th class="table-header">Ponta B</th>
                    <th class="table-header">Description</th>
                    <th class="table-header">Group</th>
                </tr>
            </thead>
            <tbody>
                {% for cable in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'datacenter:cable' cable.nep %}">{{ cable.nep }}</a>

                        </td>
                        <td class="table-cel">
                            {{ cable.dev_a }}
                        </td>
                        <td class="table-cel">
                            {{ cable.ponta_a}}
                        </td>
                        <td class="table-cel">
                            {{ cable.dev_b }}
                        </td>
                        <td class="table-cel">
                            {{ cable.ponta_b}}
                        </td>
                        <td class="table-cel">
                            {{ cable.description}}
                        </td>
                        <td class="table-cel"> 
                            {{ cable.group_dev}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="single-cable">
        <h1 class="single-cable-data">
            Nenhum Cabo Foi encontrado
        </h1>
    </div>
    {% endif %}
{% endblock content %}